name: Cleanup Orphaned Env Files

on:
  schedule:
    # Run the cleanup job every day at midnight UTC
    - cron: '0 0 * * *'

jobs:
  cleanup-env-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Find and Delete Orphaned Env Files
        run: |
          # List all env files in the .pscale/env directory
          env_files=$(find .pscale/env -name "ps-env-*.sh" || true)
          for file in $env_files; do
            # Extract the branch name from the filename
            branch_name=$(basename "$file" ".sh" | sed "s/ps-env-//")

            # Check if the branch still exists
            if ! git rev-parse --verify --quiet "$branch_name" >/dev/null 2>&1; then
              # Branch does not exist, so the file is orphaned and can be deleted
              git config user.name 'github-actions'
              git config user.email 'github-actions@github.com'
              git rm "$file"
              echo "Deleting orphaned env file: $file"
              git commit -m "Cleanup: Remove orphaned env file $file"
            else
              echo "Branch for $file still exists."
            fi
          done

          # Push changes if any files were deleted
          git_changes=$(git status --porcelain)
          if [ ! -z "$git_changes" ]; then
            git push origin main
          else
            echo "No orphaned env files to delete."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
