name: Create a Branch
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'data-access/db/prisma/schema.prisma'
    types: [opened, synchronize]

jobs:
  create_a_branch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GUTHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Create a branch
        uses: planetscale/create-branch-action@v4
        id: create_branch
        with:
          org_name: ${{secrets.ORG_NAME}}
          database_name: ${{secrets.DB_NAME}}
          branch_name: testbranch
          from: main
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
      - name: Create branch password
        uses: planetscale/create-branch-password-action@v1
        id: create_branch_password
        with:
          org_name: ${{secrets.ORG_NAME}}
          database_name: ${{secrets.DB_NAME}}
          branch_name: ${{ steps.extract_branch.outputs.branch }}
          name: 'pass-${{ steps.extract_branch.outputs.branch }}'
      - name: Get the new credentials
        run: |
          echo "Hostname: ${{ steps.create_branch_password.outputs.hostname}}"
          echo "Username: ${{ steps.create_branch_password.outputs.username}}"
          echo "Password: ${{ steps.create_branch_password.outputs.password}}"
