name: Run database migrations
on:
  pull_request:
    branches: [main]
    paths:
      - 'data-access/db/prisma/schema.prisma'

jobs:
  planetscale:
    permissions:
      pull-requests: write
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: Setup pscale
        uses: planetscale/setup-pscale-action@v1
      - name: checkout
        uses: actions/checkout@v3
      - name: Set branch name
        run: echo "PSCALE_BRANCH_NAME=$(echo ${{ github.head_ref }} | tr -cd '[:alnum:]-'| tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Create branch
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
          DB_NAME: ${{ secrets.DB_NAME }}
          ORG_NAME: ${{ secrets.ORG_NAME }}
        run: |
          set +e
          pscale branch show ${{secrets.ORG_NAME}} ${{ secrets.DB_NAME }} ${{ env.PSCALE_BRANCH_NAME }}
          exit_code=$?
          set -e

          if [ $exit_code -eq 0 ]; then
            echo "Branch exists. Skipping branch creation."
          else
            echo "Branch does not exist. Creating."
            pscale branch create ${{ secrets.DB_NAME }} ${{ env.PSCALE_BRANCH_NAME }} --wait
          fi
