name: Lint and Format Code
on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/cache-and-install.yml
    with:
      node-version: '18'
      pnpm-version: '8'

  format-and-commit:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Required to push commits back to the original repository
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set NX SHAs
        uses: nrwl/nx-set-shas@v3

      - name: Track main branch
        run: git branch --track main origin/main

      - name: Run nx format:write
        run: pnpm exec nx format:write

      - name: Check for modifications
        id: git-check
        run: |
          if git diff --quiet; then
            echo "No changes detected."
          else
            echo "::set-output name=modified::true"
          fi

      - name: Commit and Push Changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Apply linting changes"
          git push
