name: Prisma Schema Automation

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/schema.prisma'
    types: [opened, reopened, synchronize]
  pull_request_target:
    branches:
      - main
    paths:
      - '**/schema.prisma'
    types: [closed]

jobs:
  check-schema-changes:
    runs-on: ubuntu-latest
    outputs:
      schema_changed: ${{ steps.schema-change-detection.outputs.schema_changed }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Detect Schema Changes in the Most Recent Commit
        id: schema-change-detection
        run: |
          # Identifying the hash of the most recent commit
          LATEST_COMMIT_HASH=$(git rev-parse HEAD)
          echo "Latest commit hash: $LATEST_COMMIT_HASH"

          # Identifying the hash of the commit immediately before the latest
          PREVIOUS_COMMIT_HASH=$(git rev-parse HEAD~1)
          echo "Previous commit hash: $PREVIOUS_COMMIT_HASH"

          # Using git diff to check for changes in 'schema.prisma' between the two commits
          SCHEMA_CHANGE=$(git diff --name-only $PREVIOUS_COMMIT_HASH $LATEST_COMMIT_HASH -- '**/schema.prisma')
          if [ -z "$SCHEMA_CHANGE" ]; then
            echo "No schema changes detected in the most recent commit."
            echo "::set-output name=schema_changed::false"
          else
            echo "Schema changes detected in the most recent commit: $SCHEMA_CHANGE"
            echo "::set-output name=schema_changed::true"

  comment-on-pr:
    needs: check-schema-changes
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' && needs.check-schema-changes.outputs.schema_changed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Check if env file exists
        id: check-env-file
        run: |
          REF=${{ github.event.pull_request.head.ref }}
          FILE_PATH=".pscale/env/ps-env-$REF.sh"
          if [ -f "$FILE_PATH" ]; then
            echo "Env file exists."
            echo "::set-output name=env_file_exists::true"
          else
            echo "Env file does not exist."
            echo "::set-output name=env_file_exists::false"
          fi

      - name: Comment /ps-create or /ps-update on PR
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.issue.number;
            const envFileExists = ${{ steps.check-env-file.outputs.env_file_exists }};
            const message = envFileExists ? '/ps-update' : '/ps-create';
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: message,
            });
          github-token: ${{secrets.CHAMELEON_BOT}}

  prepare-for-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.review.state == 'approved' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Comment with instructions to merge
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.issue.number;
            const message = `🚀 **Action Required!** 🚀\n\n` +
                            `To finalize the changes to the schema and merge them to PlanetScale, ` +
                            `please run the command \`/ps-merge\` in the PR.\n\n` +
                            `This will trigger the merge process and apply your changes. 🌟`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: message,
            });
          github-token: ${{secrets.GITHUB_TOKEN}}
