name: Prisma Schema Automation

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/schema.prisma'
    types: [opened, reopened, synchronize]

jobs:
  check-schema-changes:
    runs-on: ubuntu-latest
    outputs:
      schema_changed: ${{ steps.schema-change-detection.outputs.schema_changed }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensure we have the entire git history for the comparison

      - name: Detect Schema Changes in the Most Recent Commit
        id: schema-change-detection
        run: |
          # Fetch all history to ensure we have the necessary data
          git fetch origin +refs/heads/*:refs/remotes/origin/* --depth=2

          # The SHA of the most recent commit on the head branch of the PR
          HEAD_SHA=${{ github.event.pull_request.head.sha }}
          echo "HEAD SHA: $HEAD_SHA"

          # The SHA of the commit immediately before the HEAD on the PR branch
          PREVIOUS_SHA=$(git rev-parse $HEAD_SHA^)
          echo "Previous SHA: $PREVIOUS_SHA"

          # Check for changes in 'schema.prisma' between the HEAD commit and its immediate predecessor
          SCHEMA_CHANGE=$(git diff --name-only $PREVIOUS_SHA $HEAD_SHA -- '**/schema.prisma')
          if [ -z "$SCHEMA_CHANGE" ]; then
            echo "No schema changes detected in the most recent commit."
            echo "::set-output name=schema_changed::false"
          else
            echo "Schema changes detected in the most recent commit: $SCHEMA_CHANGE"
            echo "::set-output name=schema_changed::true"
          fi

  comment-on-pr:
    needs: check-schema-changes
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' && needs.check-schema-changes.outputs.schema_changed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Check if env file exists
        id: check-env-file
        run: |
          REF=${{ github.event.pull_request.head.ref }}
          FILE_PATH=".pscale/env/ps-env-$REF.sh"
          if [ -f "$FILE_PATH" ]; then
            echo "Env file exists."
            echo "::set-output name=env_file_exists::true"
          else
            echo "Env file does not exist."
            echo "::set-output name=env_file_exists::false"
          fi

      - name: Comment /ps-create or /ps-update on PR
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.issue.number;
            const envFileExists = ${{ steps.check-env-file.outputs.env_file_exists }};
            const message = envFileExists ? '/ps-update' : '/ps-create';
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: message,
            });
          github-token: ${{secrets.CHAMELEON_BOT}}

  prepare-for-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.review.state == 'approved' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Comment with instructions to merge
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.issue.number;
            const message = `\
            🌟 **Important Action Required!** 🌟

            To finalize the changes to the schema and successfully merge them to PlanetScale, your action is needed. Please review the steps below:

            | Step | Action |
            | ---- | ------ |
            | 1 | Review the proposed schema changes for accuracy. |
            | 2 | Test the changes locally to ensure they work as expected. |
            | 3 | **Run the command \`/ps-merge\` in this PR's comment section.** |
            | 4 | Await the automated merge process to apply your changes. |

            This will trigger the merge process and apply your changes to PlanetScale. 🚀

            Please run \`/ps-merge\` now 🤝
            `;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: message,
            });
          github-token: ${{secrets.GITHUB_TOKEN}}
