name: Prisma Schema Automation

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/schema.prisma'
    types: [opened, reopened, synchronize]
  pull_request_target:
    branches:
      - main
    paths:
      - '**/schema.prisma'
    types: [closed]

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' }}
    steps:
      - name: Comment /ps-create on PR
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.issue.number;
            const message = '/ps-create';
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: message,
            });
          github-token: ${{secrets.GITHUB_TOKEN}}

  comment-on-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.merged == true }}
    steps:
      - name: Comment /ps-merge on merge
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.issue.number;
            const message = '/ps-merge';
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: message,
            });
          github-token: ${{secrets.GITHUB_TOKEN}}
