name: Prisma Schema Update on PlanetScale

on:
  pull_request:
    paths:
      - 'data-access/db/prisma/schema.prisma'
    types: [opened, closed, synchronize]

jobs:
  update_schema:
    runs-on: ubuntu-latest
    if: github.event.pull_request.state == 'open'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set branch name
        run: echo "PSCALE_BRANCH_NAME=$(echo '${{ github.head_ref }}' | tr -cd '[:alnum:]-' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Create a new database branch
        uses: planetscale/create-branch-action@v4
        with:
          org_name: ${{ secrets.ORG_NAME }}
          database_name: ${{ secrets.DB_NAME }}
          branch_name: ${{ env.PSCALE_BRANCH_NAME }}
          check_exists: true
          wait: true
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}

      - name: Create a password
        uses: planetscale/create-branch-password-action@v3
        with:
          org_name: ${{ secrets.ORG_NAME }}
          database_name: ${{ secrets.DB_NAME }}
          branch_name: ${{ env.PSCALE_BRANCH_NAME }}
          name: 'pass-${{ env.PSCALE_BRANCH_NAME }}'
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
        id: create_password

      - name: Override DATABASE_URL
        run: |
          echo "DATABASE_URL=mysql://${{ steps.create_password.outputs.username }}:${{ steps.create_password.outputs.password }}@${{ steps.create_password.outputs.hostname }}/${{ secrets.DB_NAME }}?sslaccept=strict" >> $GITHUB_ENV

      - name: Push schema changes to database
        run: npx prisma db push --schema=./data-access/db/prisma/schema.prisma
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}

  merge_changes:
    runs-on: ubuntu-latest
    if: github.event.pull_request.state == 'closed' && github.event.pull_request.merged == true
    needs: update_schema

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a deploy request
        uses: planetscale/create-deploy-request-action@v2
        with:
          org_name: ${{ secrets.ORG_NAME }}
          database_name: ${{ secrets.DB_NAME }}
          branch_name: ${{ github.head_ref }}
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}

      - name: Deploy the deploy request
        uses: planetscale/deploy-deploy-request-action@v4
        with:
          org_name: ${{ secrets.ORG_NAME }}
          database_name: ${{ secrets.DB_NAME }}
          number: ${{ steps.create_deploy_request.outputs.number }}
          wait: true
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
